### ISSUE TITLE
Turtlebot3 - Missing WiFi Connection during SBC setup  

### ISSUE THREAD

**Issue by sandymer07** [ROBOTIS-GIT/turtlebot3#860] opened 2022-05-17 09:46 UTC
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [ x] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [x ] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [x ] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [x ] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [x ] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [x.x.x]

7. Specify the commands or instructions to reproduce the issue.

    - ifconfig

8. Copy and Paste the error messages on terminal.

    - HERE

9. Please describe the issue in detail.

    - During the setting up of raspberry pi step in SBC setup. I am unable to find the wlan0 setting. I am getting ethernet and l0 alone. Also during this setup i am not getting a GUI based display, the turtlebot boots in a command line setup only. Please advise on how to rectify this issue and setup the turtlebot3.

**Comment by ROBOTIS-Will** [comment] 2022-05-18 01:00
@sandymer07 
You might have a corrupted wifi driver.
Have you tried something like below?
https://raspberrypi.stackexchange.com/questions/106947/wlan-module-gone-rpi-4-b

**Comment by sandymer07** [comment] 2022-05-24 04:45
@ROBOTIS-Will Thank you so much for the response. I solved the issue by installing the driver files again. Appreciate the quick response from your side.

**Comment by ROBOTIS-Will** [comment] 2022-05-25 00:43
Closing the issue as the problem is resolved.

**Closed by ROBOTIS-Will** 2022-05-25 00:43 UTC
