### ISSUE TITLE
TB3 creating a map 

### ISSUE THREAD

**Issue by Adel-kn** [ROBOTIS-GIT/turtlebot3#482] opened 2019-08-30 07:18 UTC
-Robot: waffle Pi

-SBC: Raspberry Pi 3

OS installed in SBC: Raspbian

OS installed in Remote PC: Ubuntu 16.04 LTS (Xenial Xerus)

ROS version: 1.12.14

Hello everyone,

my question is if one can create the map using SLAM in more than one time, that means continuing an already created map to extend it.

Thanks in advance

**Comment by mlherd** [comment] 2019-08-30 13:40
Duplicate of #478

**Comment by rjshim** [comment] 2019-09-05 01:24
Thanks @mlherd 
Reopen this issue if it still doesn't work. 

Regards,
Ryan

**Closed by rjshim** 2019-09-05 01:24 UTC
