### ISSUE TITLE
Windows setup issue

### ISSUE THREAD

**Issue by eszter007** [ROBOTIS-GIT/turtlebot3#614] opened 2020-07-13 11:48 UTC
As described here: https://stackoverflow.com/questions/62865143/turtlebot3-ros1-windows-setup-issue?noredirect=1#comment111172644_62865143

**Comment by ROBOTIS-Will** [comment] 2020-07-14 04:20
Hi,
Though I've just tried with the latest TurtleBot3 source code, and unable to reproduce your issue, but [this issue](https://github.com/ms-iot/ROSOnWindows/issues/218) seems related to your issue.
![image](https://user-images.githubusercontent.com/26239359/87382777-b93fed80-c5d2-11ea-821b-ed0ef9627277.png)

Thank you.

**Comment by ROBOTIS-Will** [comment] 2020-09-08 02:19
This issue is closed as there isn't any recent activity. Please feel free to reopen the issue when necessary.
Thank you.

**Closed by ROBOTIS-Will** 2020-09-08 02:19 UTC
