### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by mathgameapi** [ROBOTIS-GIT/turtlebot3#152] opened 2018-03-14 03:06 UTC
I forward the guide to create the map and load the map
I don't know why i open the rviz will got the follow result and cannot control the robotis

![img_9577](https://user-images.githubusercontent.com/703211/37381298-589eae04-2777-11e8-8bf7-c157ae16ca44.jpg)
Make the map screen

![img_9578](https://user-images.githubusercontent.com/703211/37381341-8d83cfd2-2777-11e8-88a0-440ecd8b9220.jpg)
Load the map screen

**Comment by routiful** [comment] 2018-03-15 00:07
Hi :)

The map you created is too small to drive TB3.
I recommend you would check it chapter 11.7.1 Costmap in [ROS Robot Programming](https://community.robotsource.org/t/download-the-ros-robot-programming-book-for-free/51/23)

Best regards
Darby

**Comment by mathgameapi** [comment] 2018-03-15 01:07
@routiful 

When i run the navigation sample, if the map is small will trigger the map rotation problem?

**Comment by routiful** [comment] 2018-03-20 23:38
Hi :)

Sorry for late reply.
The map rotation problem is caused by failed localization.
You can solve it by making bigger map

**Comment by mathgameapi** [comment] 2018-04-03 01:18
@routiful 

I made the map to double size still have the rotation problem.

What is the size you prefer for the map?

**Comment by routiful** [comment] 2018-04-03 23:36
Please show me how it works by capture your monitor

**Comment by mathgameapi** [comment] 2018-04-04 06:44
@routiful  
would you like to tell me how can i give you the video recording? (over 200MB)
Thanks

**Comment by mathgameapi** [comment] 2018-04-10 06:30
@routiful 
Still not work

How can i send you the video ?

**Comment by kijongGil** [comment] 2018-04-11 10:57
@mathgameapi 
Would you like to upload capture you worked?

If you want to send your video, upload your video on youtube and tell me link.

**Comment by mathgameapi** [comment] 2018-04-12 01:30
@kijongGil 

Video 1 :http://megashare.megahd.com.br/47e605e1c6204e39ae253837f04e2cb7 

Video 2 :
http://megashare.megahd.com.br/04666f9d560ed49cf5b23615416093c2 
http://megashare.megahd.com.br/2fc3558b70605755c67e7fc050fdedfe 
http://megashare.megahd.com.br/750a1aa57765b3d6069c1b60194f372a 
http://megashare.megahd.com.br/9ae81fb1d1acdde365b1d43f04890573

**Comment by kijongGil** [comment] 2018-04-12 07:38
I can't watch your video 2, It can't extract.

Your map looks troubled in video 1.

please remake a map with slam package. Then, place the TB3 in the same position when you start slam and navigation. 

If the problem isn't solved, show me the error messages in your terminal.

**Comment by mathgameapi** [comment] 2018-04-12 08:01
@kijongGil 
![img_9857 1](https://user-images.githubusercontent.com/703211/38663826-8bb081c8-3e6a-11e8-90b2-98ba0ca062a8.JPG)
![img_9858 1](https://user-images.githubusercontent.com/703211/38663844-9415f29e-3e6a-11e8-987d-3788e45c9c0f.JPG)
![img_9859 1](https://user-images.githubusercontent.com/703211/38663874-a93feaf8-3e6a-11e8-849a-c7d45d0cedae.JPG)
![img_9856 1](https://user-images.githubusercontent.com/703211/38663899-bc31abc4-3e6a-11e8-82ad-a2ff6a562ded.JPG)

**Comment by kijongGil** [comment] 2018-04-12 08:18
Could you move the TB3 out of the area surrounded by red lines? 

Because the meaning of the red line is the area where robots can not go. But, your TB3 is located in this area.

**Comment by robotpilot** [comment] 2018-04-18 22:45
I'm going to close this until you update the issue with more information. If you do so I'll reopen the issue. Also, you can reopen this issue to show this issue to the users whenever. Thanks. :)

**Closed** 2018-04-18 22:45 UTC
Labels: question, waiting for reply
